패키지 로딩하기

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import os
from google.colab import drive

drive.mount('/content/gdrive/')
os.chdir('/content/gdrive/My Drive/Colab Notebooks/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


1. txt 불러오기

In [ ]:
# data = pd.read_table(filepath_or_buffer = 'directory/filename.txt' *역슬래시가 아니라 / 일반 슬래시임에 주의!!
#              구분자 - sep = '' or ',' or '\t(탭)' -> 데이터 사이가 뭘로 구분되어있는지 확인하고 입력. 
#                      header = 'infer or 0 or None' -> 변수명(데이터의 1행)을 파이썬에서 그대로 쓴다면 infer 혹은 0. 1을 주면 2번째 행을 변수명으로 사용
#                      encoding = 'EUC=KR' ->한국어를 인식하도록...)

In [ ]:
blank = pd.read_table(filepath_or_buffer='./blank.txt', sep=' ', header=0, encoding='EUC=KR')

In [ ]:
blank

   id name  age
0   1  김수현   30
1   2  박주원   32
2   3  이영이   22
3   4  박라경   31

In [ ]:
comma = pd.read_table(filepath_or_buffer='./comma.txt', sep=',', header='infer', encoding='EUC=KR')

In [ ]:
comma

   id food drink
0   1   김치   막걸리
1   2   피자    맥주
2   3  불고기   사이다

In [ ]:
tab = pd.read_table(filepath_or_buffer='./tab.txt', sep='\t', header=0, encoding='EUC=KR')

In [ ]:
tab

   id idol nation
0   1  이준기    캐나다
1   2  박보검     호주
2   3  박보영     한국

1.2 csv : comma separated value / 흔하게 쓰이는 데이터 파일

In [ ]:
# data = pd.read_csv(filepath_or_buffer = 'directory/filename.csv'
#                    header = 'infer' or 0 or None
#                    encoding = "EUC-KR")

In [ ]:
survey = pd.read_csv('./address.csv', header=0, encoding='EUC-KR')

In [ ]:
survey

   id address  time
0   1      창동    70
1   2      길음    60
2   3      관악    35

In [ ]:
# data = pd.read_excel(io='directory/filename.xlsc'
#                      sheet_name = 'sheet name or sheet index,
#                      header = 0)

In [ ]:
reading1 = pd.read_excel('./reading.xlsx', 
                         sheet_name=0, 
                         encoding='EUC-KR'
                        )

In [ ]:
reading1

   id  books author
0   1      1   베르베르
1   2      4    오스틴
2   3      2    코엘로

2. 데이터 핸들링(Data handling) = 데이터 전처리 (Data Processing)

In [ ]:
diamonds = pd.read_excel('./diamonds.xlsx')

In [ ]:
diamonds.head(10) #맨 윗쪽에 있는 데이터 보기

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [ ]:
# data.tail() 데이터의 맨 아래쪽에 있는 데이터 보기
diamonds.tail(10)

       carat        cut color clarity  depth  table  price     x     y     z
53930   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [ ]:
# 2.2 데이터의 속성
# (1) type(data) : 데이터의 형태
type(diamonds)

pandas.core.frame.DataFrame

데이터프레임이란? <p>
행과 열로 구성되어있는 데이터 = DataFrame <p>
혹은 2차원 데이터라고도 함 <p>
Series -> key하나에 value가 여러개 할당된 데이터 구조

In [ ]:
#(2) 데이터의 모양 : 행의 갯수와 열의 갯수
# data.shape
diamonds.shape

(53940, 10)

In [ ]:
# (3) 데이터의 유형 : 데이터가 가지는 값이 무엇으로 되어있는가?
# data.dtypes
diamonds.dtypes

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

In [ ]:
# (4) 열 = 변수 = feature(Label)의 이름 확인하기 
#data.columns 
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [ ]:
# (5) 행의 이름 : index
# data.index
diamonds.index

RangeIndex(start=0, stop=53940, step=1)

In [ ]:
# (6) 데이터의 종합적인 정보
#data.info()
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [ ]:
# 2.3 데이터의 슬라이싱 = 데이터 잘라내기
# (1) 열 = 변수 = Feature = Label
# i. data['variable']
diamonds['carat']

0        0.23
1        0.21
2        0.23
3        0.29
4        0.31
         ...
53935    0.72
53936    0.72
53937    0.70
53938    0.86
53939    0.75
Name: carat, Length: 53940, dtype: float64

In [ ]:
# ii. data[['variable1','variable2']] 여러개 자르기
diamonds[['carat','price']]

       carat  price
0       0.23    326
1       0.21    326
2       0.23    327
3       0.29    334
4       0.31    335
...      ...    ...
53935   0.72   2757
53936   0.72   2757
53937   0.70   2757
53938   0.86   2757
53939   0.75   2757

[53940 rows x 2 columns]

In [ ]:
#iii. data.iloc[:,[index]] (인덱스 번호로 자르기)
diamonds.iloc[:,1]

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: object

In [ ]:
diamonds.iloc[:,[0,7,8]]

       carat     x     y
0       0.23  3.95  3.98
1       0.21  3.89  3.84
2       0.23  4.05  4.07
3       0.29  4.20  4.23
4       0.31  4.34  4.35
...      ...   ...   ...
53935   0.72  5.75  5.76
53936   0.72  5.69  5.75
53937   0.70  5.66  5.68
53938   0.86  6.15  6.12
53939   0.75  5.83  5.87

[53940 rows x 3 columns]

In [ ]:
diamonds.iloc[:,2:6]

      color clarity  depth  table
0         E     SI2   61.5   55.0
1         E     SI1   59.8   61.0
2         E     VS1   56.9   65.0
3         I     VS2   62.4   58.0
4         J     SI2   63.3   58.0
...     ...     ...    ...    ...
53935     D     SI1   60.8   57.0
53936     D     SI1   63.1   55.0
53937     D     SI1   62.8   60.0
53938     H     SI2   61.0   58.0
53939     D     SI2   62.2   55.0

[53940 rows x 4 columns]

In [ ]:
# (2) 행 슬라이스
# 행의 위치를 알때, 또는 조건을 만족하는 행
# i. 조건을 만족하는 행
#data.loc[조건, :]
#carat이 2 이상인 data 슬라이스하기
diamonds.loc[diamonds.carat >= 2, :]

       carat        cut color clarity  depth  table  price     x     y     z
11634   2.00    Premium     J      I1   61.5   59.0   5051  8.11  8.06  4.97
12246   2.06    Premium     J      I1   61.2   58.0   5203  8.10  8.07  4.95
13002   2.14       Fair     J      I1   69.4   57.0   5405  7.74  7.70  5.36
13118   2.15       Fair     J      I1   65.5   57.0   5430  8.01  7.95  5.23
13757   2.22       Fair     J      I1   66.7   56.0   5607  8.04  8.02  5.36
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
27744   2.29    Premium     I     SI1   61.8   59.0  18797  8.52  8.45  5.24
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27746   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20  8.13  5.11
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16

[2154 rows x 10 columns]

In [ ]:
# cut이 'Fair'인 데이터
diamonds.loc[diamonds.cut == 'Fair', :]

       carat   cut color clarity  depth  table  price     x     y     z
8       0.22  Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
91      0.86  Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
97      0.96  Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
123     0.70  Fair     F     VS2   64.5   57.0   2762  5.57  5.53  3.58
124     0.70  Fair     F     VS2   65.3   55.0   2762  5.63  5.58  3.66
...      ...   ...   ...     ...    ...    ...    ...   ...   ...   ...
53757   0.72  Fair     F     VS2   55.4   64.0   2724  6.06  5.97  3.34
53800   0.90  Fair     I     VS1   68.7   62.0   2732  5.83  5.79  3.99
53863   1.00  Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04  Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53882   0.71  Fair     D     VS1   65.4   59.0   2747  5.62  5.58  3.66

[1610 rows x 10 columns]

In [ ]:
# carat은 2이상이고 cut은 'fare'인 데이터
diamonds.loc[(diamonds.carat >= 2) & (diamonds.cut == 'Fair'),:] # and 는 안됨. 무조건 & 이걸로

       carat   cut color clarity  depth  table  price      x      y     z
13002   2.14  Fair     J      I1   69.4   57.0   5405   7.74   7.70  5.36
13118   2.15  Fair     J      I1   65.5   57.0   5430   8.01   7.95  5.23
13757   2.22  Fair     J      I1   66.7   56.0   5607   8.04   8.02  5.36
13929   2.00  Fair     I      I1   66.0   60.0   5667   7.78   7.74  5.10
13991   2.01  Fair     I      I1   67.4   58.0   5696   7.71   7.64  5.17
...      ...   ...   ...     ...    ...    ...    ...    ...    ...   ...
27543   2.51  Fair     H     SI2   64.7   57.0  18308   8.44   8.50  5.48
27623   2.00  Fair     G     VS2   67.6   58.0  18515   7.65   7.61  5.16
27630   4.50  Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27643   2.02  Fair     H     VS2   64.5   57.0  18565   8.00   7.95  5.14
27646   2.01  Fair     G     SI1   70.6   64.0  18574   7.43   6.64  4.69

[157 rows x 10 columns]

In [ ]:
# carat이 2이상 or cut이 Fair인 데이터
diamonds.loc[(diamonds.carat >= 2)|(diamonds.cut == 'Fair')]

       carat   cut color clarity  depth  table  price     x     y     z
8       0.22  Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
91      0.86  Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
97      0.96  Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
123     0.70  Fair     F     VS2   64.5   57.0   2762  5.57  5.53  3.58
124     0.70  Fair     F     VS2   65.3   55.0   2762  5.63  5.58  3.66
...      ...   ...   ...     ...    ...    ...    ...   ...   ...   ...
53757   0.72  Fair     F     VS2   55.4   64.0   2724  6.06  5.97  3.34
53800   0.90  Fair     I     VS1   68.7   62.0   2732  5.83  5.79  3.99
53863   1.00  Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04  Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53882   0.71  Fair     D     VS1   65.4   59.0   2747  5.62  5.58  3.66

[3607 rows x 10 columns]

In [ ]:
# ii. 행의 위치를 알 때
# data.iloc[index,:]
diamonds.iloc[[1,9,10],:]

    carat        cut color clarity  depth  table  price     x     y     z
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
9    0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
10   0.30       Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73

In [ ]:
#(3) 행과 열
#i. 조건을 만족하는 열
# data.loc[조건, 열]
# carat은 2 이상이고 cut은 'Fair'인 데이터의 'x','y','z'
diamonds.loc[(diamonds.carat >=2 )&(diamonds.cut == 'Fair'),['x','y','z']]

           x      y     z
13002   7.74   7.70  5.36
13118   8.01   7.95  5.23
13757   8.04   8.02  5.36
13929   7.78   7.74  5.10
13991   7.71   7.64  5.17
...      ...    ...   ...
27543   8.44   8.50  5.48
27623   7.65   7.61  5.16
27630  10.23  10.16  6.72
27643   8.00   7.95  5.14
27646   7.43   6.64  4.69

[157 rows x 3 columns]

In [ ]:
# ii. 위치를 알 때
# data.iloc[row_i, col_i]
# 1 ~ 10 행의 'x','y','z'
diamonds.iloc[0:10,7:10]

      x     y     z
0  3.95  3.98  2.43
1  3.89  3.84  2.31
2  4.05  4.07  2.31
3  4.20  4.23  2.63
4  4.34  4.35  2.75
5  3.94  3.96  2.48
6  3.95  3.98  2.47
7  4.07  4.11  2.53
8  3.87  3.78  2.49
9  4.00  4.05  2.39

데이터가 비대칭적일때 <p>
log변환, root 변환, inverse 변환을 통해 값을 대칭적으로 만들어 줄 수 있음 <p>
왜냐? 대부분의 통계기법은 데이터가 대칭적이라는 가정 하에 만들어졌기때문...<p>
데이터를 보고 적절한 변수를 만들어 내는 것이 실력임...

변환 = Transformation

변환을 통해 똑같은 데이터를 다양한 모델에 적용할 수 있게 됨. 특히나 대칭이 아닌 데이터를 대칭을 가정한 모델에 적용할 수 있도록 바꿔주게 되는 것...

-> **Box-Cox Transformation**

In [ ]:
# 2.4 새로운 변수 만들기(새로운 열 만들기)
# (1) 연산
# 새로운 변수명 : xyz_mean : (x + y + z) / 자유도 = 3
# data['new_variable'] = 연산 -> 데이터의 제일 오른쪽에 연산 결과열이 추가됨
diamonds['xyz_mean'] = (diamonds.x + diamonds.y + diamonds.z) / 3 
diamonds.head(3)

   carat      cut color clarity  depth  ...  price     x     y     z  xyz_mean
0   0.23    Ideal     E     SI2   61.5  ...    326  3.95  3.98  2.43  3.453333
1   0.21  Premium     E     SI1   59.8  ...    326  3.89  3.84  2.31  3.346667
2   0.23     Good     E     VS1   56.9  ...    327  4.05  4.07  2.31  3.476667

[3 rows x 11 columns]

In [ ]:
# (2) 변환(Transformation) : Box-Cox Transformaiton
# i.    log
# ii.   root
# iii.  inverse

In [ ]:
# i. price -> price_log10
diamonds['price_1og10'] = np.log10(diamonds.price)
diamonds.head()

   carat      cut color clarity  depth  ...     x     y     z  xyz_mean  price_1og10
0   0.23    Ideal     E     SI2   61.5  ...  3.95  3.98  2.43  3.453333     2.513218
1   0.21  Premium     E     SI1   59.8  ...  3.89  3.84  2.31  3.346667     2.513218
2   0.23     Good     E     VS1   56.9  ...  4.05  4.07  2.31  3.476667     2.514548
3   0.29  Premium     I     VS2   62.4  ...  4.20  4.23  2.63  3.686667     2.523746
4   0.31     Good     J     SI2   63.3  ...  4.34  4.35  2.75  3.813333     2.525045

[5 rows x 12 columns]

In [ ]:
# ii. root
#price -> price_root
diamonds['price_root'] = np.sqrt(diamonds.price) #square root의 약자
diamonds.head()

   carat      cut color clarity  ...     z  xyz_mean  price_1og10  price_root
0   0.23    Ideal     E     SI2  ...  2.43  3.453333     2.513218   18.055470
1   0.21  Premium     E     SI1  ...  2.31  3.346667     2.513218   18.055470
2   0.23     Good     E     VS1  ...  2.31  3.476667     2.514548   18.083141
3   0.29  Premium     I     VS2  ...  2.63  3.686667     2.523746   18.275667
4   0.31     Good     J     SI2  ...  2.75  3.813333     2.525045   18.303005

[5 rows x 13 columns]

In [ ]:
# iii. inverst
# price -> price_inverse
diamonds['price_inverse'] = 1 / diamonds.price
diamonds.head()

   carat      cut color  ... price_1og10  price_root  price_inverse
0   0.23    Ideal     E  ...    2.513218   18.055470       0.003067
1   0.21  Premium     E  ...    2.513218   18.055470       0.003067
2   0.23     Good     E  ...    2.514548   18.083141       0.003058
3   0.29  Premium     I  ...    2.523746   18.275667       0.002994
4   0.31     Good     J  ...    2.525045   18.303005       0.002985

[5 rows x 14 columns]

In [ ]:
# (3) 양적 자료 (수치형자료)를 질적자료(범주형 자료) 로 바꾸기
# carat -> carat_group
# 0~2 : 'light'
# 2~4 : 'middle'
# 4~6 : 'heavy'
diamonds['carat_grout'] = pd.cut(diamonds.carat,
                                 bins=[0,2,4,6], # -> 자르는 구간
                                 right = False, # -> 구간의 상한 = right, 하한 = left(False). 구간의 상한이 중복값을 가질 것인지, 상한이 중복값을 가질 것인지 정하는 파라미터 
                                 labels = ['light', 'middle', 'heavy']) 
diamonds.head()

   carat      cut color  ... price_root  price_inverse  carat_grout
0   0.23    Ideal     E  ...  18.055470       0.003067        light
1   0.21  Premium     E  ...  18.055470       0.003067        light
2   0.23     Good     E  ...  18.083141       0.003058        light
3   0.29  Premium     I  ...  18.275667       0.002994        light
4   0.31     Good     J  ...  18.303005       0.002985        light

[5 rows x 15 columns]

구간(interval or mean)을 잘 자르는 법 -> 

1. 최소값과 최대값 찾기 ( np.max() , np.min() )
2. 범위(range)구하기 (max - min)
3. 구간의 갯수를 몇개로 할까 ? 근데 이게 사실 제일 힘든 사항이다... 
  그래서! <p>[ 1+3.3*log10(n) n = 데이터의 갯수 ] 라는 공식이 있음.
4. 구간의 너비(폭) = 범위/구간의 갯수
5. 첫번째 구간에 최소값이 오도록 조정, 마지막 구간에 최대값이 오도록 구간.

    상한 = 하한 + 구간

In [ ]:
#2.5 열 = 변수 = Feature 삭제하기
# 1)del data['variable']
# 2)data.drop(['v1','v2'], axis=1, inplace = True)
# 참고 -> axis = 0 : 행, axis = 1 : 열
# inplace = True : 삭제 후의 결과를 원 데이터에 적용

In [ ]:
# (1) 하나의 열 : 'xyz_mean'
del diamonds['xyz_mean']
diamonds.head()

   carat      cut color  ... price_root  price_inverse  carat_grout
0   0.23    Ideal     E  ...  18.055470       0.003067        light
1   0.21  Premium     E  ...  18.055470       0.003067        light
2   0.23     Good     E  ...  18.083141       0.003058        light
3   0.29  Premium     I  ...  18.275667       0.002994        light
4   0.31     Good     J  ...  18.303005       0.002985        light

[5 rows x 14 columns]

In [ ]:
#(2) 2개 이상의 열 제거
diamonds.drop(['price_1og10','price_root','price_inverse','carat_grout'], axis = 1, inplace=True)
diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
# 2.6 데이터 정렬하기
# data.sort_values(by = 'variable', ascending = True or False)
# i. 하나의 열, 오름차순
diamonds.sort_values(by = 'carat', ascending=True)

       carat      cut color clarity  depth  table  price      x      y     z
31593   0.20  Premium     E     VS2   61.1   59.0    367   3.81   3.78  2.32
31597   0.20    Ideal     D     VS2   61.5   57.0    367   3.81   3.77  2.33
31596   0.20  Premium     F     VS2   62.6   59.0    367   3.73   3.71  2.33
31595   0.20    Ideal     E     VS2   59.7   55.0    367   3.86   3.84  2.30
31594   0.20  Premium     E     VS2   59.7   62.0    367   3.84   3.80  2.28
...      ...      ...   ...     ...    ...    ...    ...    ...    ...   ...
25999   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25998   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
27130   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
27630   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27415   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98

[53940 rows x 10 columns]

In [ ]:
# ii. 하나의 열 : 내림차순
diamonds.sort_values(by = 'carat', ascending=False)

       carat      cut color clarity  depth  table  price      x      y     z
27415   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27630   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27130   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
25999   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25998   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
...      ...      ...   ...     ...    ...    ...    ...    ...    ...   ...
31592   0.20  Premium     E     VS2   59.0   60.0    367   3.81   3.78  2.24
31591   0.20  Premium     E     VS2   59.8   62.0    367   3.79   3.77  2.26
31601   0.20  Premium     D     VS2   61.7   60.0    367   3.77   3.72  2.31
14      0.20  Premium     E     SI2   60.2   62.0    345   3.79   3.75  2.27
31596   0.20  Premium     F     VS2   62.6   59.0    367   3.73   3.71  2.33

[53940 rows x 10 columns]

In [ ]:
#iii. 두개의 열 : carat = 오름차순, cut = 오름차순
diamonds.sort_values(by = ['cut','carat'], ascending=True)

       carat        cut color clarity  depth  table  price      x     y     z
8       0.22       Fair     E     VS2   65.1   61.0    337   3.87  3.78  2.49
31611   0.23       Fair     G    VVS2   61.4   66.0    369   3.87  3.91  2.39
2711    0.25       Fair     D     VS1   61.2   55.0    563   4.09  4.11  2.51
28270   0.25       Fair     E     VS1   55.2   64.0    361   4.21  4.23  2.33
38153   0.25       Fair     F     SI2   54.4   64.0   1013   4.30  4.23  2.32
...      ...        ...   ...     ...    ...    ...    ...    ...   ...   ...
27024   2.74  Very Good     J     SI2   61.5   62.0  17164   8.87  8.90  5.46
27065   2.74  Very Good     H     SI2   63.3   58.0  17184   8.88  8.84  5.61
16283   3.00  Very Good     H      I1   63.1   55.0   6512   9.23  9.10  5.77
26100   3.04  Very Good     I     SI2   63.2   59.0  15354   9.14  9.07  5.75
26444   4.00  Very Good     I      I1   63.3   58.0  15984  10.01  9.94  6.31

[53940 rows x 10 columns]

In [ ]:
#iv = 두개의 열 : 둘다 내림차순
diamonds.sort_values(by = ['cut','carat'], ascending=False)

       carat        cut color clarity  depth  table  price      x     y     z
26444   4.00  Very Good     I      I1   63.3   58.0  15984  10.01  9.94  6.31
26100   3.04  Very Good     I     SI2   63.2   59.0  15354   9.14  9.07  5.75
16283   3.00  Very Good     H      I1   63.1   55.0   6512   9.23  9.10  5.77
27024   2.74  Very Good     J     SI2   61.5   62.0  17164   8.87  8.90  5.46
27065   2.74  Very Good     H     SI2   63.3   58.0  17184   8.88  8.84  5.61
...      ...        ...   ...     ...    ...    ...    ...    ...   ...   ...
2711    0.25       Fair     D     VS1   61.2   55.0    563   4.09  4.11  2.51
28270   0.25       Fair     E     VS1   55.2   64.0    361   4.21  4.23  2.33
38153   0.25       Fair     F     SI2   54.4   64.0   1013   4.30  4.23  2.32
31611   0.23       Fair     G    VVS2   61.4   66.0    369   3.87  3.91  2.39
8       0.22       Fair     E     VS2   65.1   61.0    337   3.87  3.78  2.49

[53940 rows x 10 columns]

In [ ]:
# v. 서로 정렬 방향이 다를 때 : 
diamonds.sort_values(by = ['cut', 'carat'], ascending=[True, False]) # -> ascending 값도 리스트로 만들어주면 됨

       carat        cut color clarity  depth  table  price      x      y     z
27415   5.01       Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27630   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27130   4.13       Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
23644   3.65       Fair     H      I1   67.1   53.0  11668   9.53   9.48  6.38
26431   3.40       Fair     D      I1   66.8   52.0  15964   9.42   9.34  6.27
...      ...        ...   ...     ...    ...    ...    ...    ...    ...   ...
50638   0.23  Very Good     F     VS2   59.4   57.0    402   4.06   4.09  2.42
50639   0.23  Very Good     F     VS1   61.9   58.0    402   3.90   4.02  2.45
52310   0.23  Very Good     D    VVS2   58.9   60.0    549   4.03   3.95  2.35
38273   0.21  Very Good     E     VS2   63.2   54.0    386   3.82   3.78  2.40
31598   0.20  Very Good     E     VS2   63.4   59.0    367   3.74   3.71  2.36

[53940 rows x 10 columns]

In [ ]:
#2.7 데이터 합치기
# (1) Merge : inner join, outer join(full join), outer join(left join), outer join(right join)
# (2) Concat : axis = 0(row), axis = 1(column)

In [ ]:
d1 = pd.DataFrame({'id':[1,2,4,5],
                   'age':[10,20,30,40],})
d1

   id  age
0   1   10
1   2   20
2   4   30
3   5   40

In [ ]:
d2 =  pd.DataFrame({'id':[1,3,4,6],
                   'bt':['a','b','ab','o'],})
d2

   id  bt
0   1   a
1   3   b
2   4  ab
3   6   o

In [ ]:
# merge - inner join -> primary key가 합치려고 하는 두 df 모두에 있는 것만 합침
# pd.merge(data1,data2, on= 'primary_key',how='inner')
d3 = pd.merge(d1,d2,on='id', how='inner')
d3

   id  age  bt
0   1   10   a
1   4   30  ab

In [ ]:
# merge - outer join(full join) -> 두 df를 합치는데 어느 한쪽에 값이 없는 쪽은 NaN으로 비워둠.
# pd.merge(data1,data2, on= 'primary_key',how='outer')
d4 = pd.merge(d1,d2,on='id',how='outer')
d4
d4.sort_values(by = 'id', ascending=True)

   id   age   bt
0   1  10.0    a
1   2  20.0  NaN
4   3   NaN    b
2   4  30.0   ab
3   5  40.0  NaN
5   6   NaN    o

In [ ]:
# merge - outer join(left join) -> 먼저 들어간 (left에 있는) df의 p_key가 있는 행만 합침
# pd.merge(data1, data2, on='primary_key', how='left')
d5 = pd.merge(d1,d2, on='id', how='left')
d5

   id  age   bt
0   1   10    a
1   2   20  NaN
2   4   30   ab
3   5   40  NaN

In [ ]:
# merge - outer join(right join) -> 나중에 들어간 (right에 있는) df의 p_key가 있는 행만 합침
# pd.merge(data1, data2, on='primary_key', how='right')
d6 = pd.merge(d1,d2, on='id', how='right')
d6

   id   age  bt
0   1  10.0   a
1   4  30.0  ab
2   3   NaN   b
3   6   NaN   o